In [2]:
import torch

In [3]:
#torch.masked_select(input, mask)

x=torch.randn(2,3)
mask=torch.ByteTensor([[0,0,1],[0,1,0]])
out=torch.masked_select(x,mask)

x,mask,out

(tensor([[ 0.2541,  1.2393, -0.7324],
         [-1.1040, -1.2831, -0.9491]]), tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8), tensor([-0.7324, -1.2831]))

In [4]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
y=torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1=torch.cat([x,y],dim=0)
z2=torch.cat([x,y],dim=1)

In [6]:
x, y, z1, z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [10]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack=torch.stack([x,x,x,x],dim=0)
print(x_stack)
print(x_stack.size())

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])
torch.Size([4, 2, 3])


In [11]:
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [16]:
x_1,x_2=torch.chunk(z1,2,dim=0)
y_1,y_2,y_3=torch.chunk(z1,3,dim=1)
x_1,x_2,y_1,y_2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]), tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]))

In [17]:
x1,x2=torch.split(z1,2,dim=0)
y1,y2=torch.split(z1,2,dim=1)

In [18]:
x1,x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]))

In [19]:
y1,y2

(tensor([[ 1.,  2.],
         [ 4.,  5.],
         [-1., -2.],
         [-4., -5.]]), tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [26]:
import torch.nn.init as init
x1=init.uniform(torch.FloatTensor(3,4),a=0,b=9)
x1=x1.type_as(torch.IntTensor())
x2=init.normal(torch.FloatTensor(3,4),std=0.2)
x3=init.constant(torch.FloatTensor(3,4),3.1415)
x1,x2,x3

/Users/imyeonghui/anaconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  
/Users/imyeonghui/anaconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/Users/imyeonghui/anaconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """


(tensor([[4, 7, 2, 1],
         [6, 5, 3, 2],
         [1, 3, 3, 4]], dtype=torch.int32),
 tensor([[ 0.0233, -0.3376, -0.0900,  0.0664],
         [ 0.2281,  0.0267, -0.3434, -0.2110],
         [-0.1997, -0.1016,  0.0065,  0.1784]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

/Users/imyeonghui/anaconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  """Entry point for launching an IPython kernel.
/Users/imyeonghui/anaconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  
